global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Data;
global using System.Windows.Documents;
global using System.Windows.Input;
global using System.Windows.Media;
global using System.Windows.Threading;
global using ICSharpCode.AvalonEdit;
global using ICSharpCode.AvalonEdit.CodeCompletion;
global using ICSharpCode.AvalonEdit.Document;
global using ICSharpCode.AvalonEdit.Editing;
global using ICSharpCode.AvalonEdit.Highlighting;
global using ICSharpCode.AvalonEdit.Rendering;
global using ICSharpCode.AvalonEdit.Snippets;
global using TextDocument = ICSharpCode.AvalonEdit.Document.TextDocument;
global using CommonFontWeights = System.Windows.FontWeights;
global using CommonTextEventArgs = System.Windows.Input.TextCompositionEventArgs;
global using CommonBrush = System.Windows.Media.Brush;
global using CommonImage = System.Windows.Media.ImageSource;
global using StyledProperty = System.Windows.DependencyProperty;
