# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.12.0.schema.json

PackageIdentifier: RoslynPad.RoslynPad
PackageName: RoslynPad
PackageVersion: 21.0.0
PackageLocale: en-US
PublisherUrl: https://roslynpad.net
Publisher: Eli Arbel
ShortDescription: C# editor and runner based on Roslyn
License: MIT
InstallerType: zip
ArchiveBinariesDependOnPath: true
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: ./RoslynPad.exe
    PortableCommandAlias: RoslynPad
  InstallerUrl: https://github.com/roslynpad/roslynpad/releases/download/21/RoslynPad-windows-x64.zip
  InstallerSha256: E133A23B528F011F801FCA46724CAD037CCF57623EBB2352F228F6B1A84C9118
ManifestType: singleton
ManifestVersion: 1.12.0
